language: node_js
node_js:
- '6.9.2'
env:
  global:
  - GH_REF=github.com/Cloud-Player/web
  - secure: qkGfiTKg5OO80LkzirZGc3rJsKwYu4Qvod/jFW+JSPSE7nM7M7f5BrTqgZZgpNfKsygNEAC6zHkH2xnWoAWym3UDH19kfeq2OZM5wwS92OHV30bU37g1P+Jlz5VUb1vWAAUV6iMF1CuMgI6PbfkecahsMH3g1KEKY1W5Virkd1ZErd7jMqgl1NeT43soBhK8qG7QvGhMx/6OCBQXshMK11PiXCDw0u058soRiB8KQX+3VJFCOXxYpXd2hPikxtTwhSlnUbhpqAwflfmz6XDbxF8IJvDSbuGkMlrNrnM2UplwfSn+zRSRqyvwIP/5Ga76FsMz8FoxX+6oP72TCTI696JjiYjsLa0yM4IWWs+TUOQVx3hLZeBl9mvUvy9QP4lOGrzEm7BKGlZvpQH8DZDOk6Bk7ffwEfkvq+fElCGbJAvgynZMlEZk6F5k965rP6hrECbQde4fy7EgbvqhXGjLIHHmwhpv5+oRQuVZUEwXyh5J7X5hRV7QVaCnCuKHvIj7odSGYdbaG1o9Tb95W5ENGalxWHFxEpoqYoZ//4WNRzRf1/P5v7BWsg2MuodY7sg5p4zlfzbT7kSCSeY02KFMOpKE+1PCKcM+zlfdGknj6+yal4Q8i+0MSv5D6C6M6eY9LGdq+C6pMrYpXolLHKkm0n5NechP55dpWCdcVNd1uhI=
before_install:
- npm install -g webpack
before_deploy:
- npm run build
deploy:
  - provider: script
    script: ./bin/github_pages_release.sh
    skip_cleanup: trueâ€¨
    branches:
      only:
        - master
        - feature/design
